### ISSUE TITLE
Add loklak API to widget options 

### ISSUE THREAD

**Issue by sopu** [loklak/wp-twitter-widget#1]

**Comment by mariobehling** [comment]
![selection_019](https://cloud.githubusercontent.com/assets/6399612/15934022/9aab8af8-2e7f-11e6-9b1e-8a43d4157f54.png)

Probably this should be added into the normal structure of plugins and use the css of each plugin instead of custom plugins. From a logic perspective there should probably be two areas in this settings.

## API Authentication Settings for Latest Tweets Plugin

### 1. Loklak API

Tick to use anonymous API of [loklak.org](http://loklak.org) and get plugin data through loklak (no registration and authentication required). Find out more.

### 2. Twitter API Authentication Settings
(leave as is)

**Comment by mariobehling** [comment]
Correct issue is actually here: https://github.com/loklak/wp-twitter-widget/issues/8
