### ISSUE TITLE
Add submodule to include "Use loklak API" option in settings page

### ISSUE THREAD

**Issue by sopu** [loklak/wp-twitter-widget#8]

**Comment by sopu** [comment]
The submodule has been added to loklak_php_api (7c3b982). That should solve this issue.

**Comment by mariobehling** [comment]
![selection_019](https://cloud.githubusercontent.com/assets/6399612/15934022/9aab8af8-2e7f-11e6-9b1e-8a43d4157f54.png)

Probably this should be added into the normal structure of plugins and use the css of each plugin instead of custom plugins. From a logic perspective there should probably be two areas in this settings.

## API Authentication Settings for Latest Tweets Plugin

### 1. Loklak API

Tick to use anonymous API of [loklak.org](http://loklak.org) and get plugin data through loklak (no registration and authentication required). Find out more.

### 2. Twitter API Authentication Settings
(leave as is)

Related to https://github.com/loklak/loklak_php_api/issues/35

**Comment by sopu** [comment]
@mariobehling please see the updated comment [here](https://github.com/loklak/loklak_php_api/issues/35#issuecomment-224920052). 

> Probably this should be added into the normal structure of plugins and use the css of each plugin instead of custom plugins. 
I am not sure I follow you here. The basic changes that our CSS forces are to override the inbuilt WP "settings" styles for `add_settings()` function . See [this](https://github.com/loklak/loklak_php_api/commit/db482c1fa3b6f3fb6f1f8321234dcd65cd5c2581)

I agree that it should have separate areas in settings. I had the same idea. But I thought it would be better to have it once we have the complete API.

**Comment by mariobehling** [comment]
> @mariobehling please see the updated comment here.

Looks good. Let's proceed to make it even clearer for people. We want to have loklak on the top, so users hopefully choose it right away and stop reading further.

**Comment by sopu** [comment]
@mariobehling. This is how it looks at the top. 
![selection_021](https://cloud.githubusercontent.com/assets/6399612/15939146/1d918116-2e94-11e6-863b-91a192a39ff5.png)
I am now working on adding the js code to disable auth settings when loklak is ticked.

**Comment by mariobehling** [comment]
Please change as below. Cheers.

---

## API Authentication Settings for Latest Tweets Plugin

### 1. Loklak API

Tick to use anonymous API of [loklak.org](http://loklak.org) and get plugin data through loklak (no registration and authentication required). Find out more.

### 2. Twitter API Authentication Settings
(leave as is)

**Comment by sopu** [comment]
![selection_024](https://cloud.githubusercontent.com/assets/6399612/15940389/7b91e6a2-2e99-11e6-9d10-42ddf024d74d.png)

**Comment by sopu** [comment]
f66163f fixes it!

**Comment by mariobehling** [comment]
The error message belongs to the twitter API. Please move the error message below "2. Twitter API".

**Comment by sopu** [comment]
![selection_025](https://cloud.githubusercontent.com/assets/6399612/15945786/a5e2c6e8-2eb1-11e6-8c99-6ea6cac3f433.png)

**Comment by mariobehling** [comment]
Ok, looks good. 

Could we actually pre-configure that loklak is pre-selected? So, the plugin works out of the box after the installation?

**Comment by sopu** [comment]
Pre-configuration added. https://github.com/loklak/loklak_php_api/commit/1febf42 fixes it! 
Closing.
